### ISSUE TITLE
Download encrypted media

### ISSUE THREAD

**Issue by raffam** [puemos/hls-downloader-chrome-extension#11]
Is there a way to support encrypted streams, like the ones provided by eurosportplayer.com?
I downloaded a video using this extension but it is non-playable. I suppose it is still AES-128 encrypted

[1800_complete-trimmed.m3u8.txt](https://github.com/puemos/hls-downloader-chrome-extension/files/2545159/1800_complete-trimmed.m3u8.txt)
[master_desktop_complete-trimmed.m3u8.txt](https://github.com/puemos/hls-downloader-chrome-extension/files/2545160/master_desktop_complete-trimmed.m3u8.txt)

**Comment by puemos** [comment]
I will look into this, but I think it can be done.
