### ISSUE TITLE
Saved videos do not play

### ISSUE THREAD

**Issue by briankitt** [puemos/hls-downloader-chrome-extension#12]
I downloaded my videos, they appear to be the correct length.  But VLC player will not play them.  I get no errors, they just do not work.

I am downloading Mysteries at the Museum, full episodes from 'The Travel Channel'.  You would need a provider sign on to get in, such as a cable channel subscription.

**Comment by dexter101010** [comment]
It does not play because you have downloaded an encrypted video. I think that encryption is AES 128.

At this moment, this plugin does not support downloading videos encrypted with AES 128. You can download the video but it will not be playable.
