### ISSUE TITLE
Not working with Sprout Video hosting

### ISSUE THREAD

**Issue by merkuriy** [puemos/hls-downloader-chrome-extension#13]
HLS Downlodaer v1.3.1
Example URL: https://videos.sproutvideo.com/embed/709adcb31f19e5c6f8/cd8cf2e796aa69d3

**Comment by puemos** [comment]
Thanks for opening this issue!

This website is using AES-128 Encryption [(wiki)](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) for his videos, and I will have to add a decryptor in order to play them.

I'm gonna work on it here (#16)
