### ISSUE TITLE
Crunchyroll

### ISSUE THREAD

**Issue by Mastoh** [puemos/hls-downloader-chrome-extension#14]
Please make the extension work on the Crunchyroll website.

**Comment by puemos** [comment]
Hi @Mastoh, thanks for opening this issue!

Crunchyroll is using AES-128 Encryption [(wiki)](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard) for his videos, and I will have to add a decryptor in order to play them.

I'm gonna work on it here (#16)
