### ISSUE TITLE
WebSocket connection Error

### ISSUE THREAD

**Issue by sgon00** [puemos/hls-downloader-chrome-extension#2]
In chrome://extensions/?errors=onpiiolicjjcilbnkdgkajnpknndneom:

```
WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Do I have to run websocket server locally somehow? I just followed the installation steps:

```
npm install
npm run build
chrome://extensions
LOAD UNPACKED
```

**Comment by sgon00** [comment]
FYI: I picked the directory `<path>/hls-downloader-chrome-extension/build/` when loading unpacked extension. Since the readme doesn't mention which directory to load, I guess it's the `build` directory, but not sure.

**Comment by puemos** [comment]
Hi, it's caused by the remote redux Dev tools.
`src/modules/store/index.js`
```js
const composeEnhancers = composeWithDevTools({ realtime: true, port: 8000 });
```

**Comment by sgon00** [comment]
@puemos thank you very much for your quick reply. I am not a nodejs developer so I am not sure what the real problem is. Since you add a bug label here, does it mean I just need to wait until the bug gets fixed? :) thanks a lot.

**Comment by puemos** [comment]
yeah sure! probably this weekend

**Comment by puemos** [comment]
Solved!
you can ignore the error msg or use [remotedev-server](https://github.com/zalmoxisus/remotedev-server)
