### ISSUE TITLE
Extension breaks dailymotion and rutube

### ISSUE THREAD

**Issue by illyriaandherpet** [puemos/hls-downloader-chrome-extension#28]
![Opera Snapshot_2019-07-10_154638_rutube ru](https://user-images.githubusercontent.com/52763933/61014016-2bd01a80-a33a-11e9-86ad-33bf8371a406.png)
![Opera Snapshot_2019-07-10_154801_www dailymotion com](https://user-images.githubusercontent.com/52763933/61014018-2bd01a80-a33a-11e9-883e-0ead3c6875ef.png)
Hi! I love your extension. However, whenever I try to play videos on rutube or dailymotion I have to disable this extension. Otherwise it makes the videos unplayable and say that the video is temporarily unavailable or that there's a server error. The videos play/work when I disable the extension.

**Comment by puemos** [comment]
Hi @illyriaandherpet, thanks for opening this bug!

1. **DailyMotion** seems to work, please check again.
2. Regarding **rutube**, I will need a URL in order to debug

**Comment by puemos** [comment]
this issue will be closed in 1 week
