### ISSUE TITLE
Suggestion: Automatically download.

### ISSUE THREAD

**Issue by theleetbeagle** [puemos/hls-downloader-chrome-extension#31]
Hello,

There is no reason to have to sniff the download, wait for it to complete, then separately download it, too.

Just make it so we select which stream we want to sniff, then when it's done, it just downloads it. 

Otherwise, it's a perfect extension.

**Comment by puemos** [comment]
Update:
Going to develop this feature on the weekend (hopefully)

**Comment by puemos** [comment]
Released v1.5.0

**Comment by theleetbeagle** [comment]
Hello,

Sorry to be a butt, but can you also make it automatically select a filename (and if existing filename is found, just rename it automatically, too) and confirm the download? With no dialog box at all? Trying to make this as invisible as possible for me? Sniff the download and be done until it's ready to view on my hdd, with no further interaction.
