### ISSUE TITLE
Preserving query strings in downloading segments

### ISSUE THREAD

**Issue by axlgit** [puemos/hls-downloader-chrome-extension#37]
My experience is that it does not preserve the parameters that may follow a question mark like

http://video.example.com/videos/vid003/playlist.m3u8?user=mazinga&signature=xr483ntc1totn8yty9n245x42t

hence if segments inside playlist.m3u8 are specified as follows

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-TARGETDURATION:4
#EXTINF:10.000,
segment001.ts
#EXTINF:10.000,
segment002.ts
#EXTINF:10.000,
segment003.ts
#EXTINF:10.000,
segment004.ts
#EXTINF:10.000,
segment005.ts

and the website accepts requests only with 

http://video.example.com/videos/vid003/segment001.ts?user=mazinga&signature=xr483ntc1totn8yty9n245x42t

HLS fails at downloading them.

I wrote a bash script that used as input the URL caught by HLS and by preserving the query string, that sometimes is used to authenticate users, and I was able to download all the segments.

I would fork the code but I'm new to chrome extensions, I'm just learning now...

**Comment by puemos** [comment]
solved on https://github.com/puemos/hls-downloader-chrome-extension/releases/tag/v2.0.0
