### ISSUE TITLE
Auto Save

### ISSUE THREAD

**Issue by theleetbeagle** [puemos/hls-downloader-chrome-extension#40]
Hello, this is Nick the guy that asked for Auto Download a few mos ago which you quickly implemented.

Can you also do Auto Save? On the streaming site I use this for, I'll eventually get a dialog box after it's done downloading, asking for save location. I would like this all automated and saved to my default download folder.

Also, note, that it doesn't catch the file extension. It's always a long string of characters (which is fine), but to automatically add .mp4 at the end would be great.

Thanks.
-Nick.

**Comment by jwshields** [comment]
Why was this labelled `wontfix`?

**Comment by puemos** [comment]
@jwshields it was a mistake :)

**Comment by jwshields** [comment]
Ah!
Somehow when I looked earlier, the page did not show the issue being reopened & tag removed.
My apologies, and thank you for the answer!

**Comment by puemos** [comment]
released on v1.7.0
