### ISSUE TITLE
NanN% shown on the Downloads pane - doesn't download anything

### ISSUE THREAD

**Issue by zb-z** [puemos/hls-downloader-chrome-extension#43]
Repro URL: 

http://serije.lako.biz/epizode/junacinasegdoba.php?ep=1

Sniffer (apparently) does it's part fine, shows 3 items with different bandwidths. 

Oh and "Stream Recorder" (https://www.hlsloader.com/index.html) downloads it just fine, in "Normal Mode" => stream is OK (normal mode is when it recognizes stream(s) and is able to drain and assemble pieces on it's own).

That particular server might be a bit problematic (the player on that page trips after 5-15 min) but not at the very beginning. "Stream Recorder" gets correct number of blocks and fetches them without a hiccup.

**Comment by puemos** [comment]
Thank you for submitting this bug, I'll solve it ASAP

**Comment by puemos** [comment]
Solved, please wait for the update
