### ISSUE TITLE
download saved as 0-sized file

### ISSUE THREAD

**Issue by zb-z** [puemos/hls-downloader-chrome-extension#45]
OK here's another one - same server - nothing better for catching bugs than a shaky server :-)

Repro URL: http://serije.lako.biz/epizode/vratadovrata.php?ep=1.Specijal

Sniffer OK, take 712x400. It's 2 bugs - there shouldn't be 2 items listed as 712x400 - the same issue happens with all other resolutions. Might be related.

BTW is hls-downloader-chrome-extension/public/ installable in Dev mode? Or do you have another place with releases?

**Comment by puemos** [comment]
Solved on v1.6.3
