### ISSUE TITLE
.cache/... in git(hub) diffs

### ISSUE THREAD

**Issue by zb-z** [puemos/hls-downloader-chrome-extension#46]
Just one example:

https://github.com/puemos/hls-downloader-chrome-extension/commit/9c04ca1c93d427e94241239003412f4c4ef5ca22

https://github.com/puemos/hls-downloader-chrome-extension/blob/9c04ca1c93d427e94241239003412f4c4ef5ca22/.cache/03/21c8bd04e39c80d057a33d0b7bacb3.json

Notice enormous amount of trash it generated.

.cache/... should never, ever be present on a git server

**Comment by puemos** [comment]
Absolutely! it was an unfortunate mistake, was fixed in a419b4ff92fee020594d1962d4011f67d6fb1607
