### ISSUE TITLE
Unwanted Websocket to /socketcluster

### ISSUE THREAD

**Issue by arigon** [puemos/hls-downloader-chrome-extension#48]
Hello

in commit [8d7bee0](https://github.com/puemos/hls-downloader-chrome-extension/commit/8d7bee050b85948b11c352d2ada8bdefda078286) in file _src/modules/store/index.js_ you removed the development-server-only part of the websocket connection... this is now causing unwanted connections to my local development server on localhost:8000 for /socketcluster..

Best regards
Alex

**Comment by puemos** [comment]
Thanks 😊
