### ISSUE TITLE
another M3U8

### ISSUE THREAD

**Issue by uiuiuiui1** [puemos/hls-downloader-chrome-extension#5]
Hi !

Another one, for your consideration...

https://www. iomovies. to /movie/hearts-of-darkness-a-filmmakers-apocalypse-ENqjz97j/watch#GvEPBoNeyK7GavoX

here's the M3U8 - 
https://luna4.istream.space/(4)(87871)(2)(4-f21-f25-f29-f20)(0)(2)(9)(4)(1)(2)()()(5)(1)(f27--59-a707845-8)(27)(5a527149--)(d-94c4)()(5555f4f20)(c-a)(-)(2)(07a)(0)(8-a)(2)(1)(17a)(0)(9-a)(--)(7f2d-1-5-2747)(72)(d21)(1)(f5)/video.m3u8

an mp4 part - 
https://luna4.istream.space/(4)(87871)(2)(4-f21-f25-f29-f20)(0)(2)(9)(4)(1)(2)()()(5)(1)(f27--59-a707845-8)(27)(5a527149--)(d-94c4)()(5555f4f20)(c-a)(-)(2)(07a)(0)(8-a)(2)(1)(17a)(0)(9-a)(--)(7f2d-1-5-2747)(72)(d21)(1)(f5)/360/015200v8.mp4 

thanks

**Comment by puemos** [comment]
Caused by protected files #4
