### ISSUE TITLE
After deleting a download the download page is crashing 

### ISSUE THREAD

**Issue by KaIKuxy** [puemos/hls-downloader-chrome-extension#51]
**Describe the bug**
Unable to show the page of Downloads, but the videos are still able to be downloaded and then show the Save page.
I've used this extension for several months and this bug only shows today.

**To Reproduce**
Unknown

**Screenshots**
![image](https://user-images.githubusercontent.com/17746583/72873107-d50dab00-3ca3-11ea-8979-63d94b002edb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser chrome
 - Version 79.0.3945.117

**Comment by puemos** [comment]
Hi @KaIKuxy, thanks for opening this bug!
can you please provide a link to a video that is causing the issue?

**Comment by KaIKuxy** [comment]
> Hi @KaIKuxy, thanks for opening this bug!
> can you please provide a link to a video that is causing the issue?

Sorry bro it's a private course video from University.

**Comment by puemos** [comment]
I found the problem. will solve it ASAP

**Comment by puemos** [comment]
The cause of the problem is deleting a download, meanwhile in order to temporarily solve the problem please disable the extension and then enable it again.

![image](https://user-images.githubusercontent.com/13174025/72874435-4c6a2b80-3cf2-11ea-8db7-dbf6565b756f.png)
