### ISSUE TITLE
Add Ability to Copy download link

### ISSUE THREAD

**Issue by saeid0034** [puemos/hls-downloader-chrome-extension#55]
I think it would be great if you add a feature for copy file **download** link to use in some other **app**

**Comment by puemos** [comment]
Already exists.
<img width="435" alt="Screen Shot 2020-01-28 at 11 54 18 AM" src="https://user-images.githubusercontent.com/13174025/73257977-09fa9000-41c5-11ea-93e4-8b79673f5e16.png">

**Comment by puemos** [comment]
Do you mean the final result file?

**Comment by saeid0034** [comment]
> Already exists.
> <img alt="Screen Shot 2020-01-28 at 11 54 18 AM" width="435" src="https://user-images.githubusercontent.com/13174025/73257977-09fa9000-41c5-11ea-93e4-8b79673f5e16.png">

In fact, this is exactly what I wanted
But because when i click on this icon No **pop-ups** or **messages** came to me about link was copyed, I didn't notice the link being copied
Other than that when i click on this icon, Apart from copying the stream link, It also entered the **download page** and dont give me any **messages** About link was copyed...
It is better to receive a message when **links copyed**
it will be perefect if you add this on next **update**

**Comment by puemos** [comment]
Already been released on v1.7.2 that is still `Pending Review` on the chrome store
