### ISSUE TITLE
Filename disambiguation problem

### ISSUE THREAD

**Issue by zb-z** [puemos/hls-downloader-chrome-extension#58]
HLS downloader basically takes the page title and turns it into a filename. There are a lot of pages these days that want to be fancy SPA pages and that means that for N actual streams the title remains constant. A few times the "name conflict" ended up as several streams "materializing" with the actual data from the last or first (forgot which one, not going to go through that anguish again :-)

For a start it needs to disambiguate on it's own, say to append an ordinal.

Then, just at is has a [copy] micro-buttons now it needs a button or a field for [rename] and it needs to "internalize" new name - meaning that the next stream for that page won't have to disambiguate at all.

For a repro and latter trials/test you can use the same link from a prior bug: https://www7.putlockertv.to/watch/impulse-1.kk7o6/vvxzqm4

MyCloud row, take [1] - download, then [2], then [3] (if you really have to, there's no point asking for more trouble :-).

**Comment by puemos** [comment]
https://developer.chrome.com/extensions/examples/api/downloads/download_filename_controller/bg.js

**Comment by puemos** [comment]
https://github.com/puemos/hls-downloader-chrome-extension/issues/63
