### ISSUE TITLE
 Simultaneous connection and download speed settings.

### ISSUE THREAD

**Issue by niyari** [puemos/hls-downloader-chrome-extension#59]
Some sites may return an error if the number of connections is limited or if the amount of data is exceeded during a certain period of time.
Even if an error is returned, it does not retry, so a file with missing information may remain.

https://github.com/puemos/hls-downloader-chrome-extension/blob/deefc332a12e4df0f2b89b61853cbca784e55959/src/modules/downloads/sagas/index.js#L56

**Comment by puemos** [comment]
Great idea! It will take me some time to develop it.
Thanks!

**Comment by puemos** [comment]
added on https://github.com/puemos/hls-downloader-chrome-extension/releases/tag/v2.0.0
