### ISSUE TITLE
Error when running "npm run build"

### ISSUE THREAD

**Issue by KaIKuxy** [puemos/hls-downloader-chrome-extension#61]
I was encountered with an error when I tried to run "npm run build".

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.41.2"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:

  /home/kaiku/Workspace/hls-downloader-chrome-extension/node_modules/webpack (version: 4.41.6)

I thought it was caused by a higher version of webpack globally, but it's not, and I found

kaiku@DESKTOP-G3V0L9B:~/Workspace/hls-downloader-chrome-extension$ npm ls webpack
@1.7.2 /home/kaiku/Workspace/hls-downloader-chrome-extension
├─┬ @storybook/react@5.2.8
│ ├─┬ @storybook/core@5.2.8
│ │ ├─┬ corejs-upgrade-webpack-plugin@2.2.0
│ │ │ └── webpack@4.41.6  deduped
│ │ └── webpack@4.41.6  deduped
│ └── webpack@4.41.6
└─┬ react-scripts@3.3.0
  └── webpack@4.41.2

It's from storybook
[2020-02-17T22_37_30_806Z-debug.log](https://github.com/puemos/hls-downloader-chrome-extension/files/4216598/2020-02-17T22_37_30_806Z-debug.log)

**Comment by puemos** [comment]
Thanks, I'll take a look (you're welcome to open a new pull request 😎)

**Comment by puemos** [comment]
I'm using `yarn` in this project and therefor `yarn.lock` is making sure that everyone should have the same result.
please try to use `yarn` and tell me if you still having issues.
Thanks!

**Comment by KaIKuxy** [comment]
I'll try with yarn, thanks!
